[project]
name = "chinese-idioms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cerebras-cloud-sdk>=1.50.1",
    "datasets>=4.1.0",
    "gradio>=4.44.1",
    "ollama>=0.5.3",
    "pycccedict>=1.2.0",
    "pypinyin>=0.55.0",
<<<<<<< HEAD
=======
    "sentence-transformers>=2.2.2",
    "numpy>=1.26.0",
>>>>>>> 660f6fb (organizing files into src folder etc.)
]

[dependency-groups]
dev = [
    "python-dotenv>=1.1.1",
    "watchfiles>=1.1.0",
     "black>=25.1.0",
    "isort>=6.0.1",
    "pylint>=3.3.8",
    "pytest>=8.4.2",
]
